pub(super) const UALBERTA_HIGH_SCHOOL_TOPICS: [&'static str; 18] = [
    "arabic",
    "art",
    "biology",
    "chemistry",
    "chinese",
    "english",
    "french",
    "german",
    "italian",
    "japanese",
    "latin",
    "mathematics",
    "physics",
    "punjabi",
    "science",
    "social studies",
    "spanish",
    "ukranian",
];

pub(super) const UALBERTA_TOPICS: [&'static str; 323] = [
    "abrod", "acctg", "admi", "adram", "afns", "agrmt", "ales", "als", "anat", "anate", "andr",
    "angl", "an sc", "anthe", "anthr", "arab", "arec", "art", "arte", "asl", "astro", "auacc",
    "auart", "aubio", "auche", "aucla", "aucri", "aucsc", "aucsl", "audra", "aueap", "aueco",
    "auedc", "auefx", "aueng", "auenv", "aueps", "aufar", "aufre", "augds", "augeo", "auger",
    "auhis", "auhum", "auids", "auind", "aulan", "aulat", "aumat", "aumgt", "aumus", "aupac",
    "auped", "auphi", "auphy", "aupol", "aupsy", "aurel", "ausca", "ausci", "ausoc", "auspa",
    "aussc", "austa", "bioch", "biocm", "bioen", "bioin", "biol", "biole", "bioph", "b law", "bme",
    "bot", "btm", "buec", "bus", "cats", "ccals", "cedul", "cell", "ch e", "chem", "chim", "china",
    "chrtc", "chrtp", "civ e", "class", "c lit", "cme", "cmput", "comm", "csd", "csl", "da", "dac",
    "dance", "dds", "dent", "des", "devdu", "dh", "d hyg", "drama", "eap", "eas", "easia", "ece",
    "econ", "econe", "edct", "edel", "edes", "edfx", "edhs", "edit", "edps", "edpy", "edse", "edu",
    "edu f", "edu m", "edu p", "edu s", "encmp", "encs", "engg", "engl", "eng m", "en ph", "ent",
    "env e", "epe", "espa", "etcan", "etin", "et re", "exagc", "exales", "exare", "exart", "exasb",
    "exba", "exch", "excpe", "excst", "exelp", "exen", "exerm", "exfrm", "exgen", "exgl", "exiapp",
    "exiic", "exldr", "exlgp", "exlup", "exmgt", "exns", "exopt", "exos", "exph", "exri", "exscma",
    "exsdp", "exsm", "exsph", "ext", "fin", "f med", "folk", "forec", "franc", "fr ed", "fren",
    "fs", "geneq", "genet", "geoph", "germ", "greek", "gsj", "gtotc", "hadvc", "hebr", "hecol",
    "he ed", "hgeo", "hindi", "hist", "histe", "hume", "imin", "imine", "infor", "int d", "ipg",
    "irish", "ital", "japan", "kin", "korea", "krls", "ksr", "labmp", "la st", "latin", "law",
    "ling", "lingq", "lis", "litt", "mace", "mafsj", "ma ph", "mark", "ma sc", "mat e", "math",
    "mathq", "mdgen", "meas", "mec e", "med", "m edu", "mgtsc", "micrb", "micre", "min e", "mint",
    "mlcs", "mlsci", "mm", "mmi", "m reg", "mst", "music", "musiq", "nano", "neuro", "norse",
    "norw", "ns", "nu fs", "nurs", "nutr", "ob gy", "obiol", "occth", "om", "oncol", "ophth",
    "pac", "paed", "paleo", "pet e", "pgde", "pgme", "pharm", "phil", "phile", "phys", "physe",
    "physl", "physq", "plan", "pl sc", "pmcol", "pol s", "polsh", "port", "psstc", "psyce",
    "psych", "psyci", "pther", "punj", "raddi", "radth", "rehab", "relig", "ren r", "rls", "rsch",
    "r soc", "russ", "sansk", "scand", "sci", "sc inf", "sc po", "scsoc", "scsp", "sem", "slav",
    "soc", "socie", "span", "sph", "sprit", "stat", "statq", "sts", "surg", "sust", "swed",
    "taaco", "taafi", "taamg", "taamk", "taarh", "taatc", "t des", "thes", "ukr", "univ", "wgs",
    "wkexp", "write", "wrs", "zool", "zoole",
];
